### ISSUE TITLE
When running "./playcheck.sh & cava", cava stops and the comment "User defined signal 2" is printed.

### ISSUE THREAD

**Issue by benesposito** [elmo-space/cavapify#5]
https://unix.stackexchange.com/questions/38589/why-does-sigusr1-cause-process-to-be-terminated/38590

I have determined that the issue is due to the line "pkill -USR2 cava". I am not fluent in Linux enough to debug this myself. Any solution?

**Comment by str-dst** [comment]
pkill -USR2 cava sends the SIGUSR2 signal to the cava process which, in the case of cava, tells the process to reload it's color configuration (which is obviously needed to change the color of the bars).
See: https://github.com/karlstav/cava/blob/master/README.md#configuration

In your case it seems that either cava is too old (older versions of cava lack the user signal feature) or one of the depency libraries is too old and therefore prevents cava from functioning in the correct way.

it's not an issue with this script.

**Comment by benesposito** [comment]
Installing cava-git instead of cava fixed the problem.
